### ISSUE TITLE
Registration of new user does not work - Iteration 2

### ISSUE THREAD

**Issue by jpowell321** [stansakl/VolunTrackKU#5]
Defect Report 01 submitted.

Dump:

Notice: Undefined variable: conn in C:\Users\April\Documents\IT810\VolunTrackKU\src\voluntrack\DBManager.php on line 55

Fatal error: Uncaught Error: Call to a member function prepare() on null in C:\Users\April\Documents\IT810\VolunTrackKU\src\voluntrack\DBManager.php:72 Stack trace: #0 C:\Users\April\Documents\IT810\VolunTrackKU\src\voluntrack\register.php(14): voluntrack\DBManager->register_user('Jim', 'Tompson', 'r', 'jimto@email.com', '$2y$10$FV24anA5...') #1 {main} thrown in C:\Users\April\Documents\IT810\VolunTrackKU\src\voluntrack\DBManager.php on line 72

**Comment by stansakl** [comment]
Should be fixed in the latest code. Problem was attempting to use self instead of $this.
